### ISSUE TITLE
virtualbox-guest-additions causes random errors

### ISSUE THREAD

**Issue by ssergey2018** [gregory-lee-bartholomew/fedora-on-zfs#2]
When putting a system with virtualbox-guest-additions installed in a transit system on virtualbox, it causes random errors when downloading packages inside qemu.
The virtualbox-guest-additions package is contraindicated for the transit system. Random errors like this occur. Only the names of failed packages are changed.
Error: Error downloading packages:
  libtirpc-1.3.3-1.rc2.fc39.x86_64: Cannot download, all mirrors were already tried without success
an error has occurred on line 31 of scripts/pre/0.sh
Traceback (most recent call last):
  File "/usr/sbin/anaconda", line 374, in <module>
    startup_utils.run_pre_scripts(kspath)
  File "/usr/lib64/python3.12/site-packages/pyanaconda/startup_utils.py", line 406, in run_pre_scripts
    kickstart.preScriptPass(ks_path)
  File "/usr/lib64/python3.12/site-packages/pyanaconda/kickstart.py", line 319, in preScriptPass
    runPreScripts(ksparser.handler.scripts)
  File "/usr/lib64/python3.12/site-packages/pyanaconda/kickstart.py", line 420, in runPreScripts
    script.run("/")
  File "/usr/lib64/python3.12/site-packages/pyanaconda/kickstart.py", line 128, in run
    errorHandler.cb(ScriptError(self.lineno, err))
  File "/usr/lib64/python3.12/site-packages/pyanaconda/errors.py", line 226, in cb
    raise exn
pyanaconda.errors.ScriptError

**Comment by gregory-lee-bartholomew** [comment]
If there is a conflict between VirtualBox's networking configuration and QEMU's user networking, I'm not sure that is a problem that I will be able to solve. QEMU supports other networking configurations, but the way the install script is written, it takes advantage of the `hostfwd` and `guestfwd` parameters that are unique to user networking ([SLiRP](https://wiki.qemu.org/Documentation/Networking#User_Networking_(SLIRP))).

If you have ideas, I'm all ears. Otherwise, I might have to concede that this script will not work from within VirtualBox.

Does VirtualBox support other networking modes that might work better with QEMU's user networking? Since QEMU's user networking seems to work OK on physical hosts, I'm tempted to say the problem lies with VirtualBox.

**Comment by gregory-lee-bartholomew** [comment]
If the problem really is random (it *sometimes* works), then adding the following line just before the first `dnf install ...` command in `config/override.ks` *might* be a viable workaround.

```
echo 'retries=0' >> /etc/dnf/dnf.conf
```

The above line should cause dnf to retry forever. If it doesn't work, you might need to use the `Ctrl`+`A`, `X` hotkey to kill the installer.

Edit: Because dnf commands are also run in a chrooted env, you'll probably have to add the following to the `%pre-install` section of `config/override.ks` as well.

```
mkdir -p "$ANACONDA_ROOT_PATH/etc/dnf"
echo 'retries=0' >> "$ANACONDA_ROOT_PATH/etc/dnf/dnf.conf"
```

**Comment by ssergey2018** [comment]
I don't know which option is better. I refused virtualbox-guest-additions and the problem disappeared. The main motivation for using virtualbox-guest-additions was that the system installation time was too long. About 2 hours is a lot, so that's what I tried to try using virtualbox-guest-additions
I think putting a note in the documentation regarding this problem will be enough
If it makes sense at all

**Comment by gregory-lee-bartholomew** [comment]
Does removing virtualbox-guest-additions also resolve the other problem you mentioned in the other issue report about the zfs-dracut package missing from the installed system? If so, I guess I can close that issue.

> I think putting a note in the documentation regarding this problem will be enough

Sure. In fact, I'll link to this issue report and leave this issue open so that someone else might come along and offer a solution or workaround.

Thanks. 🙂

**Comment by ssergey2018** [comment]
The presence of virtualbox-guest-additions on the transit system prevents the installation process from completing. Out of 5-7 attempts, I still could not finish the installation
